local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set('n', "<leader>ha", mark.add_file)
vim.keymap.set('n', "<leader>hu", ui.toggle_quick_menu)

vim.keymap.set('n', "hr1", function() ui.nav_file(1) end)
vim.keymap.set('n', "hr2", function() ui.nav_file(2) end)
vim.keymap.set('n', "hr3", function() ui.nav_file(3) end)
vim.keymap.set('n', "hr4", function() ui.nav_file(4) end)
vim.keymap.set('n', "hr5", function() ui.nav_file(5) end)
vim.keymap.set('n', "hr6", function() ui.nav_file(6) end)
vim.keymap.set('n', "hr7", function() ui.nav_file(7) end)
vim.keymap.set('n', "hr8", function() ui.nav_file(8) end)
vim.keymap.set('n', "hr9", function() ui.nav_file(9) end)
vim.keymap.set('n', "hr10", function() ui.nav_file(10) end)
vim.keymap.set('n', "hr11", function() ui.nav_file(11) end)
vim.keymap.set('n', "hr12", function() ui.nav_file(12) end)
vim.keymap.set('n', "hr13", function() ui.nav_file(13) end)
vim.keymap.set('n', "hr14", function() ui.nav_file(14) end)
vim.keymap.set('n', "hr15", function() ui.nav_file(15) end)
vim.keymap.set('n', "hr16", function() ui.nav_file(16) end)
vim.keymap.set('n', "hr17", function() ui.nav_file(17) end)
vim.keymap.set('n', "hr18", function() ui.nav_file(18) end)
vim.keymap.set('n', "hr19", function() ui.nav_file(19) end)
vim.keymap.set('n', "hr20", function() ui.nav_file(20) end)
