vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pv", vim.cmd.Ex)
vim.keymap.set({'n', 'x'}, 'cp', '"+y')
vim.keymap.set({'n', 'x'}, 'cv', '"+p')
vim.keymap.set({'n', 'x'}, 'x', '"_x')
vim.keymap.set('n', '<leader>a', ':keepjumps normal! ggVG<cr>')
vim.keymap.set({'n', 'x'}, '<leader>cw', '<C-w-w>', {desc = 'Change window'})
vim.keymap.set({'n', 'x'}, 'tbnt', '<cmd>tabnext<cr>', {desc = ':tabnext'})
vim.keymap.set({'n', 'x'}, 'tbpr', '<cmd>tabprev<cr>', {desc = ':tabprev'})
vim.keymap.set({'n', 'x'}, 'tbet', '<cmd>tabedit<cr>', {desc = ':tabedit'})
vim.keymap.set({'n', 'x'}, '<leader>cmd', '<cmd>terminal cmd<cr>', {desc = ':terminal cmd'})
vim.keymap.set('v', 'J', ":m '>+1<CR>gv=gv", {desc = 'move selected lines down'})
vim.keymap.set('v', 'K', ":m '<-2<CR>gv=gv", {desc = 'move selected lines up'})
vim.keymap.set('n', 'J', "mzJ`z", {desc = 'do the same thing as original J but cursor remains same'})
vim.keymap.set('n', '<C-d>', "<C-d>zz", {desc = 'half page down but cursor remains at center of screen'})
vim.keymap.set('n', '<C-u>', "<C-u>zz", {desc = 'half page up but cursor remains at center of screen'})
vim.keymap.set('x', '<leader>rp', "\"_dP", {desc = 'replaces copied word over current word without changing copied buffer'})
vim.keymap.set("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set("i", "<leader>tcw", "<C-w-w>", {desc = 'change window out of terminal'})
